-- Auto-generated seed (regex parser)
BEGIN;
INSERT INTO counties (name, code) VALUES ('Baringo County', 'baringo_county');
INSERT INTO counties (name, code) VALUES ('Bomet County', 'bomet_county');
INSERT INTO counties (name, code) VALUES ('Bungoma County', 'bungoma_county');
INSERT INTO counties (name, code) VALUES ('Busia County', 'busia_county');
INSERT INTO counties (name, code) VALUES ('Elgeyo-Marakwet County', 'elgeyo_marakwet_county');
INSERT INTO counties (name, code) VALUES ('Embu County', 'embu_county');
INSERT INTO counties (name, code) VALUES ('Garissa County', 'garissa_county');
INSERT INTO counties (name, code) VALUES ('Homa Bay County', 'homa_bay_county');
INSERT INTO counties (name, code) VALUES ('Isiolo County', 'isiolo_county');
INSERT INTO counties (name, code) VALUES ('Kajiado County', 'kajiado_county');
INSERT INTO counties (name, code) VALUES ('Kakamega County', 'kakamega_county');
INSERT INTO counties (name, code) VALUES ('Kericho County', 'kericho_county');
INSERT INTO counties (name, code) VALUES ('Kiambu County', 'kiambu_county');
INSERT INTO counties (name, code) VALUES ('Kirinyaga County', 'kirinyaga_county');
INSERT INTO counties (name, code) VALUES ('Kisii County', 'kisii_county');
INSERT INTO counties (name, code) VALUES ('Kisumu County', 'kisumu_county');
INSERT INTO counties (name, code) VALUES ('Kitui County', 'kitui_county');
INSERT INTO counties (name, code) VALUES ('Kwale County', 'kwale_county');
INSERT INTO counties (name, code) VALUES ('Laikipia County', 'laikipia_county');
INSERT INTO counties (name, code) VALUES ('Machakos County', 'machakos_county');
INSERT INTO counties (name, code) VALUES ('Makueni County', 'makueni_county');
INSERT INTO counties (name, code) VALUES ('Mandera County', 'mandera_county');
INSERT INTO counties (name, code) VALUES ('Marsabit County', 'marsabit_county');
INSERT INTO counties (name, code) VALUES ('Meru County', 'meru_county');
INSERT INTO counties (name, code) VALUES ('Migori County', 'migori_county');
INSERT INTO counties (name, code) VALUES ('Murang''a County', 'murang_a_county');
INSERT INTO counties (name, code) VALUES ('Nairobi County', 'nairobi_county');
INSERT INTO counties (name, code) VALUES ('Nakuru County', 'nakuru_county');
INSERT INTO counties (name, code) VALUES ('Nandi County', 'nandi_county');
INSERT INTO counties (name, code) VALUES ('Narok County', 'narok_county');
INSERT INTO counties (name, code) VALUES ('Nyamira County', 'nyamira_county');
INSERT INTO counties (name, code) VALUES ('Nyandarua County', 'nyandarua_county');
INSERT INTO counties (name, code) VALUES ('Nyeri County', 'nyeri_county');
INSERT INTO counties (name, code) VALUES ('Samburu County', 'samburu_county');
INSERT INTO counties (name, code) VALUES ('Siaya County', 'siaya_county');
INSERT INTO counties (name, code) VALUES ('Tharaka-Nithi County', 'tharaka_nithi_county');
INSERT INTO counties (name, code) VALUES ('Trans-Nzoia County', 'trans_nzoia_county');
INSERT INTO counties (name, code) VALUES ('Turkana County', 'turkana_county');
INSERT INTO counties (name, code) VALUES ('Uasin Gishu County', 'uasin_gishu_county');
INSERT INTO counties (name, code) VALUES ('Vihiga County', 'vihiga_county');
INSERT INTO counties (name, code) VALUES ('Wajir County', 'wajir_county');
INSERT INTO counties (name, code) VALUES ('West Pokot County', 'west_pokot_county');

INSERT INTO constituencies (name, code, county_id) VALUES ('Garissa Township', 'garissa_township', (SELECT id FROM counties WHERE code='kwale_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Balambala', 'balambala', (SELECT id FROM counties WHERE code='kwale_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lagdera', 'lagdera', (SELECT id FROM counties WHERE code='kwale_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Dadaab', 'dadaab', (SELECT id FROM counties WHERE code='kwale_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Fafi', 'fafi', (SELECT id FROM counties WHERE code='kwale_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ijara', 'ijara', (SELECT id FROM counties WHERE code='kwale_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Garissa Township', 'garissa_township', (SELECT id FROM counties WHERE code='garissa_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Balambala', 'balambala', (SELECT id FROM counties WHERE code='garissa_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lagdera', 'lagdera', (SELECT id FROM counties WHERE code='garissa_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Dadaab', 'dadaab', (SELECT id FROM counties WHERE code='garissa_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Fafi', 'fafi', (SELECT id FROM counties WHERE code='garissa_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ijara', 'ijara', (SELECT id FROM counties WHERE code='garissa_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Wajir North', 'wajir_north', (SELECT id FROM counties WHERE code='wajir_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Wajir East', 'wajir_east', (SELECT id FROM counties WHERE code='wajir_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tarbaj', 'tarbaj', (SELECT id FROM counties WHERE code='wajir_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Wajir West', 'wajir_west', (SELECT id FROM counties WHERE code='wajir_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Eldas', 'eldas', (SELECT id FROM counties WHERE code='wajir_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Wajir South', 'wajir_south', (SELECT id FROM counties WHERE code='wajir_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mandera West', 'mandera_west', (SELECT id FROM counties WHERE code='mandera_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Banissa', 'banissa', (SELECT id FROM counties WHERE code='mandera_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mandera North', 'mandera_north', (SELECT id FROM counties WHERE code='mandera_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mandera South', 'mandera_south', (SELECT id FROM counties WHERE code='mandera_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mandera East', 'mandera_east', (SELECT id FROM counties WHERE code='mandera_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lafey', 'lafey', (SELECT id FROM counties WHERE code='mandera_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Moyale', 'moyale', (SELECT id FROM counties WHERE code='marsabit_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('North Horr', 'north_horr', (SELECT id FROM counties WHERE code='marsabit_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Saku', 'saku', (SELECT id FROM counties WHERE code='marsabit_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Laisamis', 'laisamis', (SELECT id FROM counties WHERE code='marsabit_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Isiolo North', 'isiolo_north', (SELECT id FROM counties WHERE code='isiolo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Isiolo South', 'isiolo_south', (SELECT id FROM counties WHERE code='isiolo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Igembe South', 'igembe_south', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Igembe Central', 'igembe_central', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Igembe North', 'igembe_north', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tigania West', 'tigania_west', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tigania East', 'tigania_east', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('North Imenti', 'north_imenti', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Buuri', 'buuri', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Central Imenti', 'central_imenti', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('South Imenti', 'south_imenti', (SELECT id FROM counties WHERE code='meru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Maara', 'maara', (SELECT id FROM counties WHERE code='tharaka_nithi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Chuka/Igambang''ombe', 'chuka_igambang_ombe', (SELECT id FROM counties WHERE code='tharaka_nithi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tharaka', 'tharaka', (SELECT id FROM counties WHERE code='tharaka_nithi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Manyatta', 'manyatta', (SELECT id FROM counties WHERE code='embu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Runyenjes', 'runyenjes', (SELECT id FROM counties WHERE code='embu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mbeere South', 'mbeere_south', (SELECT id FROM counties WHERE code='embu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mbeere North', 'mbeere_north', (SELECT id FROM counties WHERE code='embu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mwingi North', 'mwingi_north', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mwingi West', 'mwingi_west', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mwingi Central', 'mwingi_central', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitui West', 'kitui_west', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitui Rural', 'kitui_rural', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitui Central', 'kitui_central', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitui East', 'kitui_east', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitui South', 'kitui_south', (SELECT id FROM counties WHERE code='kitui_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Masinga', 'masinga', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Yatta', 'yatta', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kangundo', 'kangundo', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Matungulu', 'matungulu', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kathiani', 'kathiani', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mavoko', 'mavoko', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Machakos Town', 'machakos_town', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mwala', 'mwala', (SELECT id FROM counties WHERE code='machakos_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mbooni', 'mbooni', (SELECT id FROM counties WHERE code='makueni_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kilome', 'kilome', (SELECT id FROM counties WHERE code='makueni_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kaiti', 'kaiti', (SELECT id FROM counties WHERE code='makueni_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Makueni', 'makueni', (SELECT id FROM counties WHERE code='makueni_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kibwezi West', 'kibwezi_west', (SELECT id FROM counties WHERE code='makueni_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kibwezi East', 'kibwezi_east', (SELECT id FROM counties WHERE code='makueni_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kinangop', 'kinangop', (SELECT id FROM counties WHERE code='nyandarua_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kipipiri', 'kipipiri', (SELECT id FROM counties WHERE code='nyandarua_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ol Kalou', 'ol_kalou', (SELECT id FROM counties WHERE code='nyandarua_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ol Jorok', 'ol_jorok', (SELECT id FROM counties WHERE code='nyandarua_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ndaragwa', 'ndaragwa', (SELECT id FROM counties WHERE code='nyandarua_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tetu', 'tetu', (SELECT id FROM counties WHERE code='nyeri_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kieni', 'kieni', (SELECT id FROM counties WHERE code='nyeri_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mathira', 'mathira', (SELECT id FROM counties WHERE code='nyeri_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Othaya', 'othaya', (SELECT id FROM counties WHERE code='nyeri_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mukurweini', 'mukurweini', (SELECT id FROM counties WHERE code='nyeri_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nyeri Town', 'nyeri_town', (SELECT id FROM counties WHERE code='nyeri_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mwea', 'mwea', (SELECT id FROM counties WHERE code='kirinyaga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Gichugu', 'gichugu', (SELECT id FROM counties WHERE code='kirinyaga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ndia', 'ndia', (SELECT id FROM counties WHERE code='kirinyaga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kirinyaga Central', 'kirinyaga_central', (SELECT id FROM counties WHERE code='kirinyaga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kangema', 'kangema', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mathioya', 'mathioya', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kiharu', 'kiharu', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kigumo', 'kigumo', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Maragwa', 'maragwa', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kandara', 'kandara', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Gatanga', 'gatanga', (SELECT id FROM counties WHERE code='murang_a_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Gatundu South', 'gatundu_south', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Gatundu North', 'gatundu_north', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Juja', 'juja', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Thika Town', 'thika_town', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ruiru', 'ruiru', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Githunguri', 'githunguri', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kiambu', 'kiambu', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kiambaa', 'kiambaa', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kabete', 'kabete', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kikuyu', 'kikuyu', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Limuru', 'limuru', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lari', 'lari', (SELECT id FROM counties WHERE code='kiambu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Turkana North', 'turkana_north', (SELECT id FROM counties WHERE code='turkana_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Turkana West', 'turkana_west', (SELECT id FROM counties WHERE code='turkana_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Turkana Central', 'turkana_central', (SELECT id FROM counties WHERE code='turkana_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Loima', 'loima', (SELECT id FROM counties WHERE code='turkana_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Turkana South', 'turkana_south', (SELECT id FROM counties WHERE code='turkana_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Turkana East', 'turkana_east', (SELECT id FROM counties WHERE code='turkana_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kapenguria', 'kapenguria', (SELECT id FROM counties WHERE code='west_pokot_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Sigor', 'sigor', (SELECT id FROM counties WHERE code='west_pokot_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kacheliba', 'kacheliba', (SELECT id FROM counties WHERE code='west_pokot_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Pokot South', 'pokot_south', (SELECT id FROM counties WHERE code='west_pokot_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Samburu West', 'samburu_west', (SELECT id FROM counties WHERE code='samburu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Samburu North', 'samburu_north', (SELECT id FROM counties WHERE code='samburu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Samburu East', 'samburu_east', (SELECT id FROM counties WHERE code='samburu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kwanza', 'kwanza', (SELECT id FROM counties WHERE code='trans_nzoia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Endebess', 'endebess', (SELECT id FROM counties WHERE code='trans_nzoia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Saboti', 'saboti', (SELECT id FROM counties WHERE code='trans_nzoia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kiminini', 'kiminini', (SELECT id FROM counties WHERE code='trans_nzoia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Cherangany', 'cherangany', (SELECT id FROM counties WHERE code='trans_nzoia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Soy', 'soy', (SELECT id FROM counties WHERE code='uasin_gishu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Turbo', 'turbo', (SELECT id FROM counties WHERE code='uasin_gishu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Moiben', 'moiben', (SELECT id FROM counties WHERE code='uasin_gishu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ainabkoi', 'ainabkoi', (SELECT id FROM counties WHERE code='uasin_gishu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kapseret', 'kapseret', (SELECT id FROM counties WHERE code='uasin_gishu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kesses', 'kesses', (SELECT id FROM counties WHERE code='uasin_gishu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Marakwet East', 'marakwet_east', (SELECT id FROM counties WHERE code='elgeyo_marakwet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Marakwet West', 'marakwet_west', (SELECT id FROM counties WHERE code='elgeyo_marakwet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Keiyo North', 'keiyo_north', (SELECT id FROM counties WHERE code='elgeyo_marakwet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Keiyo South', 'keiyo_south', (SELECT id FROM counties WHERE code='elgeyo_marakwet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tinderet', 'tinderet', (SELECT id FROM counties WHERE code='nandi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Aldai', 'aldai', (SELECT id FROM counties WHERE code='nandi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nandi Hills', 'nandi_hills', (SELECT id FROM counties WHERE code='nandi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Chesumei', 'chesumei', (SELECT id FROM counties WHERE code='nandi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Emgwen', 'emgwen', (SELECT id FROM counties WHERE code='nandi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mosop', 'mosop', (SELECT id FROM counties WHERE code='nandi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tiaty', 'tiaty', (SELECT id FROM counties WHERE code='baringo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Baringo North', 'baringo_north', (SELECT id FROM counties WHERE code='baringo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Baringo Central', 'baringo_central', (SELECT id FROM counties WHERE code='baringo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Baringo South', 'baringo_south', (SELECT id FROM counties WHERE code='baringo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mogotio', 'mogotio', (SELECT id FROM counties WHERE code='baringo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Eldama Ravine', 'eldama_ravine', (SELECT id FROM counties WHERE code='baringo_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Laikipia West', 'laikipia_west', (SELECT id FROM counties WHERE code='laikipia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Laikipia East', 'laikipia_east', (SELECT id FROM counties WHERE code='laikipia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Laikipia North', 'laikipia_north', (SELECT id FROM counties WHERE code='laikipia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Molo', 'molo', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Njoro', 'njoro', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Naivasha', 'naivasha', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Gilgil', 'gilgil', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kuresoi South', 'kuresoi_south', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kuresoi North', 'kuresoi_north', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Subukia', 'subukia', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Rongai', 'rongai', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bahati', 'bahati', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nakuru Town West', 'nakuru_town_west', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nakuru Town East', 'nakuru_town_east', (SELECT id FROM counties WHERE code='nakuru_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kilgoris', 'kilgoris', (SELECT id FROM counties WHERE code='narok_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Emurua Dikirr', 'emurua_dikirr', (SELECT id FROM counties WHERE code='narok_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Narok North', 'narok_north', (SELECT id FROM counties WHERE code='narok_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Narok East', 'narok_east', (SELECT id FROM counties WHERE code='narok_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Narok South', 'narok_south', (SELECT id FROM counties WHERE code='narok_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Narok West', 'narok_west', (SELECT id FROM counties WHERE code='narok_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kajiado North', 'kajiado_north', (SELECT id FROM counties WHERE code='kajiado_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kajiado Central', 'kajiado_central', (SELECT id FROM counties WHERE code='kajiado_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kajiado East', 'kajiado_east', (SELECT id FROM counties WHERE code='kajiado_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kajiado West', 'kajiado_west', (SELECT id FROM counties WHERE code='kajiado_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kajiado South', 'kajiado_south', (SELECT id FROM counties WHERE code='kajiado_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kipkelion East', 'kipkelion_east', (SELECT id FROM counties WHERE code='kericho_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kipkelion West', 'kipkelion_west', (SELECT id FROM counties WHERE code='kericho_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ainamoi', 'ainamoi', (SELECT id FROM counties WHERE code='kericho_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bureti', 'bureti', (SELECT id FROM counties WHERE code='kericho_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Belgut', 'belgut', (SELECT id FROM counties WHERE code='kericho_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Sigowet–Soin', 'sigowet_soin', (SELECT id FROM counties WHERE code='kericho_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Sotik', 'sotik', (SELECT id FROM counties WHERE code='bomet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Chepalungu', 'chepalungu', (SELECT id FROM counties WHERE code='bomet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bomet East', 'bomet_east', (SELECT id FROM counties WHERE code='bomet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bomet Central', 'bomet_central', (SELECT id FROM counties WHERE code='bomet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Konoin', 'konoin', (SELECT id FROM counties WHERE code='bomet_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lugari', 'lugari', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Likuyani', 'likuyani', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Malava', 'malava', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lurambi', 'lurambi', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Navakholo', 'navakholo', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mumias West', 'mumias_west', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mumias East', 'mumias_east', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Matungu', 'matungu', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Butere', 'butere', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Khwisero', 'khwisero', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Shinyalu', 'shinyalu', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ikolomani', 'ikolomani', (SELECT id FROM counties WHERE code='kakamega_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Vihiga', 'vihiga', (SELECT id FROM counties WHERE code='vihiga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Sabatia', 'sabatia', (SELECT id FROM counties WHERE code='vihiga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Hamisi', 'hamisi', (SELECT id FROM counties WHERE code='vihiga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Luanda', 'luanda', (SELECT id FROM counties WHERE code='vihiga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Emuhaya', 'emuhaya', (SELECT id FROM counties WHERE code='vihiga_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mount Elgon', 'mount_elgon', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Sirisia', 'sirisia', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kabuchai', 'kabuchai', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bumula', 'bumula', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kanduyi', 'kanduyi', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Webuye East', 'webuye_east', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Webuye West', 'webuye_west', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kimilili', 'kimilili', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Tongaren', 'tongaren', (SELECT id FROM counties WHERE code='bungoma_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Teso North', 'teso_north', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Teso South', 'teso_south', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nambale', 'nambale', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Matayos', 'matayos', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Butula', 'butula', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Funyula', 'funyula', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Budalangi', 'budalangi', (SELECT id FROM counties WHERE code='busia_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ugenya', 'ugenya', (SELECT id FROM counties WHERE code='siaya_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ugunja', 'ugunja', (SELECT id FROM counties WHERE code='siaya_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Alego Usonga', 'alego_usonga', (SELECT id FROM counties WHERE code='siaya_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Gem', 'gem', (SELECT id FROM counties WHERE code='siaya_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bondo', 'bondo', (SELECT id FROM counties WHERE code='siaya_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Rarieda', 'rarieda', (SELECT id FROM counties WHERE code='siaya_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kisumu East', 'kisumu_east', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kisumu West', 'kisumu_west', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kisumu Central', 'kisumu_central', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Seme', 'seme', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nyando', 'nyando', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Muhoroni', 'muhoroni', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nyakach', 'nyakach', (SELECT id FROM counties WHERE code='kisumu_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kasipul', 'kasipul', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kabondo Kasipul', 'kabondo_kasipul', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Karachuonyo', 'karachuonyo', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Rangwe', 'rangwe', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Homa Bay Town', 'homa_bay_town', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ndhiwa', 'ndhiwa', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Suba North', 'suba_north', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Suba South', 'suba_south', (SELECT id FROM counties WHERE code='homa_bay_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Rongo', 'rongo', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Awendo', 'awendo', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Suna East', 'suna_east', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Suna West', 'suna_west', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Uriri', 'uriri', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nyatike', 'nyatike', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kuria West', 'kuria_west', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kuria East', 'kuria_east', (SELECT id FROM counties WHERE code='migori_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bonchari', 'bonchari', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('South Mugirango', 'south_mugirango', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bomachoge Borabu', 'bomachoge_borabu', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bobasi', 'bobasi', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Bomachoge Chache', 'bomachoge_chache', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nyaribari Masaba', 'nyaribari_masaba', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nyaribari Chache', 'nyaribari_chache', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitutu Chache North', 'kitutu_chache_north', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitutu Chache South', 'kitutu_chache_south', (SELECT id FROM counties WHERE code='kisii_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitutu Masaba', 'kitutu_masaba', (SELECT id FROM counties WHERE code='nyamira_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('West Mugirango', 'west_mugirango', (SELECT id FROM counties WHERE code='nyamira_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('North Mugirango', 'north_mugirango', (SELECT id FROM counties WHERE code='nyamira_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Borabu', 'borabu', (SELECT id FROM counties WHERE code='nyamira_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Westlands', 'westlands', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kitisuru', 'kitisuru', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Dagoretti North', 'dagoretti_north', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kilimani', 'kilimani', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Dagoretti South', 'dagoretti_south', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mutu-ini', 'mutu_ini', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Lang''ata', 'lang_ata', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Karen', 'karen', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kibra', 'kibra', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Laini Saba', 'laini_saba', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Roysambu', 'roysambu', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Githurai', 'githurai', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kasarani', 'kasarani', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Clay City', 'clay_city', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Ruaraka', 'ruaraka', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Babadogo', 'babadogo', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Embakasi South', 'embakasi_south', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Imara Daima', 'imara_daima', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Embakasi North', 'embakasi_north', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kariobangi North', 'kariobangi_north', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Embakasi Central', 'embakasi_central', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kayole North', 'kayole_north', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Embakasi East', 'embakasi_east', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Upper Savanna', 'upper_savanna', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Embakasi West', 'embakasi_west', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Umoja I', 'umoja_i', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Makadara', 'makadara', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Makongeni', 'makongeni', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Kamukunji', 'kamukunji', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Pumwani', 'pumwani', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Starehe', 'starehe', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Nairobi Central', 'nairobi_central', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Mathare', 'mathare', (SELECT id FROM counties WHERE code='nairobi_county')) ;
INSERT INTO constituencies (name, code, county_id) VALUES ('Hospital', 'hospital', (SELECT id FROM counties WHERE code='nairobi_county')) ;
COMMIT;